<?php

namespace EspritClubsBundle\Repository;

/**
 * evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class evenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function chercherEvent($titre){

$query = $this->getEntityManager()->createQuery("select v from EspritClubsBundle:evenement v where v.titre = '$titre'");
        return $query->getResult();
    }
}
